### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by phourniner** [parzival-space/powercord-pradio#1]
Does this play the radio for all to hear in the voice chat? Either way, it's not working. I give the stream URL in the settings, and nothing happens when I join a voice chat. The stream url is http://www.c895.org/mp3/? so it should be working properly, since the stream plays in my browser just fine.

Thank you.

**Comment by parzival-space** [comment]
Hey @phourniner,

your stream URL is incorrect.
This is your correct stream URL: http://knhc-ice.streamguys1.com/live

Sadly, it looks like the server is for whatever reason blocking the connection:
<img src="https://i.imgur.com/D7K6bHh.png">

There is basically nothing I can do to help you.

**Comment by phourniner** [comment]
Ah, that's unfortunate. How did you find that URL? I just want to know in case I need this type of thing in the future.

Thank you anyway for your help!

**Comment by parzival-space** [comment]
There is more than one way to get the stream URL:

1. If you are lucky, the radio station will give you the direct URL on their website.

2. When the radio stations provides you a .m3u playlist file, and you open this file in your favorite text editor, you can basically copy one of the stream URL and use it in the plugin:
<img src="https://i.imgur.com/zN8y43U.png">

3. The last one is a bit more complicated, but it works on every website:
    When you open the website with your radio stations web player, you have to press ctrl+i to open your browser developer tools.
    Then open your 'Network' tab:
    <img src="https://i.imgur.com/runqWrg.png">
    You will get a list with all loaded resources and established connections.
    Now you need to find the entry with the Initiator 'media', for example:
    <img src="https://i.imgur.com/Ib5hllN.png">
    When you double click this entry it should open the resource in a new tab.
    In your address bar you will find the URL of your stream.
