### ISSUE TITLE
Discord detecting weird activity on their servers

### ISSUE THREAD

**Issue by Goseale** [parzival-space/powercord-pradio#2]
I have a friend that owns a radio station and while listening to the station my friend mentioned that the IP that gets sent to the station is Discord's one instead of mine.
My worry is that since it's coming from discord, they might be able to detect it and terminate my account

**Comment by parzival-space** [comment]
Its not sending the IP of Discord. Its sending the Origin of the Request. This means that the Radio station knows that you loaded the stream from discord.com, but the data is send to your client (your IP). So there is basically nothing that is send to the Discord servers.

The Discord server do not know anything about the communication between your client and the radio station.

**Comment by Goseale** [comment]
Ty for the quick reply
