### ISSUE TITLE
"Text=" "Song="

### ISSUE THREAD

**Issue by MemLiveOn** [parzival-space/powercord-pradio#3]
https://tgb.is-inside.me/1ZHrPEZs.png

Should be pretty self-explanatory. It should just show the name of the station/song. Currently using Alt 96.1

http://n3ca-e2.revma.ihrhls.com/zc2593?rj-ttl=5&rj-tok=AAABe1OoBJ0AnysFRqD_ykxWPQ

**Comment by MemLiveOn** [comment]
Added but separate issue (didn't feel like making a new issue): Mute button doesn't work.

**Comment by parzival-space** [comment]
how often do you see this issue? I cant reproduce this at the moment.

**Comment by parzival-space** [comment]
closed due to inactivity
