### ISSUE TITLE
Problems with listen.moe

### ISSUE THREAD

**Issue by ArjixWasTaken** [parzival-space/powercord-pradio#4]
https://docs.listen.moe/

It doesn't play anything, but it correctly shows the track's title.
Also it fails to show japanese in the album name.

**Comment by parzival-space** [comment]
This is actually a problem that is caused by your radio station.
<img src="https://i.imgur.com/fGwhPms.png">

The error message basically means, that the station is blocking requests from 'discord.com' (aka. your Discord client).
I actually can not do anything to fix this, because this error is out of my reach.

I am sorry, but this station just won't work with the plugin.

**Comment by ArjixWasTaken** [comment]
> This is actually a problem that is caused by your radio station.
> ![](https://camo.githubusercontent.com/c9362e61005198e7b4b7308b0264598ccb2e801db6453ba0b941c860d7439b12/68747470733a2f2f692e696d6775722e636f6d2f66477768506d732e706e67)
> 
> The error message basically means, that the station is blocking requests from 'discord.com' (aka. your Discord client).
> I actually can not do anything to fix this, because this error is out of my reach.
> 
> I am sorry, but this station just won't work with the plugin.

hmm, iirc you can use nodejs to make the request, since nodejs is packed with electron, right?
CORS is enforced by the browser, in this case electron
nodejs is not a browser

ignore me if I am saying nonsense

**Comment by parzival-space** [comment]
I do not want to say that this is impossible.
But unfortunately, I don't have enough time for this plugin at the moment.

Maybe in the near future, when I have more time.

**Comment by parzival-space** [comment]
Sorry, I do not have the time to implement this and I do not think I will have the time in the near future.
Also, this would not work in Powercord v3.

Again, I am sorry, but I think I have to cancel this request.
